# Site settings
title: "Cecily Chen's Personal Works"
email: "cccancc@cn.ibm.com"
description: > # this means to ignore newlines until "baseurl:"
 This page is about the my personal experience and UI/UX design works. All materials are only for personal use.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https:/cccancc.github.io.com" # the base hostname & protocol for your site
#url: "127.0.0.1:4000" # the base hostname & protocol for your site
WeChat: 394708994
github_username:  cccancc


# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Cool Option 1
    link: www.myawesomelink.com
  option2:
    name: Cool Option 2
    link: www.myawesomelink.com
  option3:
    name: Cool Option 3
    link: www.myawesomelink.com

disqus: true
disqus_shortname: 'gdgmanagua'

# Build settings
markdown: kramdown
